---
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

processors:
  attributes:
    actions:
      - action: upsert
        key: service.namespace
        value: dreamkast
      - action: upsert
        key: service.name
        value: dreamkast
      - action: upsert
        key: deployment.environment.name
        value: stg
  resource/dreamkast:
    attributes:
      - action: upsert
        key: service.name
        value: dreamkast
      - action: upsert
        key: deployment.environment.name
        value: stg
  transform/mackerel_logs:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          # JSON文字列を構造化ログに変換
          - set(body, ParseJSON(body))
            where IsString(body)

          # log level -> OpenTelemetry Severity
          - set(severity_text, body["level"])
            where IsMap(body) and body["level"] != nil

          - set(severity_number, SEVERITY_NUMBER_DEBUG)
            where IsMap(body) and body["level"] == "DEBUG"

          - set(severity_number, SEVERITY_NUMBER_INFO)
            where IsMap(body) and body["level"] == "INFO"

          - set(severity_number, SEVERITY_NUMBER_WARN)
            where IsMap(body) and (body["level"] == "WARN" or body["level"] == "WARNING")

          - set(severity_number, SEVERITY_NUMBER_ERROR)
            where IsMap(body) and body["level"] == "ERROR"

          - set(severity_number, SEVERITY_NUMBER_FATAL)
            where IsMap(body) and body["level"] == "FATAL"

          # Mackerelの構造化ログ検索用
          - set(body["deployment.environment.name"], resource.attributes["deployment.environment.name"])
            where IsMap(body) and resource.attributes["deployment.environment.name"] != nil

          - set(body["service.name"], resource.attributes["service.name"])
            where IsMap(body) and resource.attributes["service.name"] != nil

  resourcedetection:
    detectors: [env, ecs]
    timeout: 2s
    override: false
  batch/logs:
    send_batch_size: 1000
    send_batch_max_size: 1000
  tail_sampling:
    policies:
      - name: include http 5xx response status
        type: numeric_attribute
        numeric_attribute:
          key: http.response.status_code
          min_value: 500
          max_value: 599
      - name: include http 5xx status
        type: numeric_attribute
        numeric_attribute:
          key: http.status_code  # dreamkastはこの古い仕様で送っている
          min_value: 500
          max_value: 599
      - name: include slow http
        type: latency
        latency:
          threshold_ms: 6000
      - name: include random sample
        type: probabilistic
        probabilistic:
          sampling_percentage: 5

exporters:
  mackerelotlp:
  otlphttp/loki:
      endpoint: https://stg.loki.cloudnativedays.jp/otlp

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [attributes, resourcedetection]
      exporters: [mackerelotlp]
    traces:
      receivers: [otlp]
      processors: [attributes, resourcedetection, tail_sampling]
      exporters: [mackerelotlp]
    logs:
      receivers: [otlp]
      processors:
        - attributes
        - resource/dreamkast
        - resourcedetection
        - transform/mackerel_logs
        - batch/logs
      exporters: [mackerelotlp,otlphttp/loki]
  extensions: [health_check]
