{
 "title": "CloudNativeDays Deep Dive",
 "time": { "from": "now-60d", "to": "now" },
 "panels": [
  {
   "title": "このダッシュボードについて",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# CloudNativeDays Deep Dive\n\nこのダッシュボードは、CloudNativeDaysの[公式サイト](https://cloudnativedays.jp/)の過去60日間のアクセス情報を可視化しています。\n\n一体、どのようなユーザな方たちが見られているのかを少し覗いてみましょう!!\n\n"
   }
  },
  {
   "title": "サイトアクセス数 (国別)",
   "type": "stat",
   "description": "https://cloudnativedays.jp にアクセスされた方を国別に表示しています。",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "select nullif(geo.country,'') as country, count(distinct user_pseudo_id) as users from `cloudnativedays-o11y.analytics_363617797.events_*` where geo.country is not null group by country order by users desc"
    }
   ]
  },
  {
   "title": "サイトアクセス数 (都道府県別)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "select nullif(geo.region,'') as region, count(distinct user_pseudo_id) as users from `cloudnativedays-o11y.analytics_363617797.events_*` where geo.country = 'Japan' and geo.region is not null group by region order by users desc"
    }
   ]
  },
  {
   "title": "使用しているデバイス",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "select device.category as device_category, count(distinct user_pseudo_id) as users from `cloudnativedays-o11y.analytics_363617797.events_*` where device.category is not null group by device_category order by users desc"
    }
   ]
  },
  {
   "title": "使用しているOS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "select ifnull(device.operating_system, '') as OS, count(distinct user_pseudo_id) as users from `cloudnativedays-o11y.analytics_363617797.events_*` where device.operating_system is not null group by OS order by users desc"
    }
   ]
  },
  {
   "title": "使用しているブラウザ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "select ifnull(device.web_info.browser, '') as browsers, count(distinct user_pseudo_id) as users from `cloudnativedays-o11y.analytics_363617797.events_*` where device.web_info.browser is not null group by browsers order by users desc"
    }
   ]
  }
 ]
}