{
 "title": "CNDF2023 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "queryString", "query": { "query": "label_values(queryString)" } }
  ]
 },
 "panels": [
  {
   "title": "Dreamkast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dreamkastダッシュボード使い方",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Dreamkastダッシュボード使い方\n\n主に、CloudNative Days Fukuoka 2023で用いている配信プラットフォーム`Dreamkastのメトリクス`を表示するダッシュボードです。\n動画配信のメトリクスに加え、イベントの登録者数などのイベント全体に関わるメトリクスを表示する役割を持ちます。\n\n現在表示しているメトリクスは下記の通りです。\n\n- CNDF2023視聴者数: Dreamkastを通して`動画視聴しているユーザ数`を表示しています。\n- 累計チャット数: Dreamkastの動画の横に配置している`チャットへの累計投稿数`を表示しています。\n- CNDF2023参加登録者数: `CNDF2023に参加登録いただいた人数`を表示しています。\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CNDF2023視聴者数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(sum(dreamkast_track_viewer_count) by(instance))",
     "legendFormat": "CNDF2023視聴者数"
    }
   ]
  },
  {
   "title": "CNDF2023視聴者数(最新値)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "人" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(dreamkast_track_viewer_count) by(instance))"
    }
   ]
  },
  {
   "title": "累積チャット数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(sum(dreamkast_chat_count) by(instance))",
     "legendFormat": "累積チャット数"
    }
   ]
  },
  {
   "title": "累積チャット数(最新値)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(dreamkast_chat_count) by(instance))"
    }
   ]
  },
  {
   "title": "CNDF2023参加登録者数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(dreamkast_registrants_count{conference_id=\"9\"})",
     "legendFormat": "CNDF2023登録者数"
    }
   ]
  },
  {
   "title": "CNDF2023参加登録者数(最新値)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "人" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(dreamkast_registrants_count{conference_id=\"9\"})"
    }
   ]
  }
 ]
}