{
 "title": "#cndt2022 proposal",
 "time": { "from": "2022-09-15T15:00:00.000Z", "to": "2022-10-10T15:00:00.000Z" },
 "panels": [
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count (dreamkast_talks_id)" }
   ]
  },
  {
   "title": "プロポーザル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "count (dreamkast_talks_id)" }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_talks_id) by (talk_difficulty)",
     "legendFormat": "{{talk_difficulty}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*59.*\"})",
     "legendFormat": "Architect - システム設計"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*60.*\"})",
     "legendFormat": "Developer - システム開発"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*61.*\"})",
     "legendFormat": "App-developer - アプリケーション開発"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*62.*\"})",
     "legendFormat": "Operator/sys-admin - 運用管理/システム管理"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*63.*\"})",
     "legendFormat": "Cxo/biz - ビジネス層"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*64.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*65.*\"})",
     "legendFormat": "Dev/QA（開発環境）"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*66.*\"})",
     "legendFormat": "Poc（検証）"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*67.*\"})",
     "legendFormat": "Production（本番環境）"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*68.*\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "登壇方法",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"presentation_method\", params=~\".*73.*\"})",
     "legendFormat": "現地登壇"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"presentation_method\", params=~\".*74.*\"})",
     "legendFormat": "オンライン登壇"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"presentation_method\", params=~\".*75.*\"})",
     "legendFormat": "事前収録"
    }
   ]
  },
  {
   "title": "スライドと動画の公開可否",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*69.*\"})",
     "legendFormat": "All okay - スライド・動画両方ともに公開可"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*70.*\"})",
     "legendFormat": "Only Slide - スライドのみ公開可"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*71.*\"})",
     "legendFormat": "NG - いずれも公開不可（来場者限定のコンテンツ）"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*72.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "セッション時間",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"session_time\", params=~\".*76.*\"})",
     "legendFormat": "40min (full session)"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"session_time\", params=~\".*77.*\"})",
     "legendFormat": "20min (half session)"
    }
   ]
  },
  {
   "title": "言語",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"language\", params=~\".*78.*\"})",
     "legendFormat": "JA"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"language\", params=~\".*79.*\"})",
     "legendFormat": "EN"
    }
   ]
  }
 ]
}