{
 "title": "オンサイト監視用",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "push_time_seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "push_time_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "people_counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "people_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "co2_conce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "co2_conce", "legendFormat": "{{job}}" }
   ]
  }
 ]
}