{
 "title": "CNsec2022 Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "queryString", "query": { "query": "label_values(queryString)" } }
  ]
 },
 "panels": [
  { "title": "Dreamkast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dreamkastダッシュボード使い方",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Dreamkastダッシュボード使い方\n\n主に、CNSec2022で用いている配信プラットフォーム`Dreamkastのメトリクス`を表示するダッシュボードです。\n動画配信のメトリクスに加え、イベントの登録者数などのイベント全体に関わるメトリクスを表示する役割を持ちます。\n\n現在表示しているメトリクスは下記の通りです。\n\n- CNSec2022視聴者数: Dreamkastを通して`動画視聴しているユーザ数`を表示しています。\n- 累計チャット数: Dreamkastの動画の横に配置している`チャットへの累計投稿数`を表示しています。\n- CNSec2022参加登録者数: `CNSec2022に参加登録いただいた人数`を表示しています。\n\n"
   }
  },
  {
   "title": "CNSec2022視聴者数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(sum(dreamkast_track_viewer_count) by(instance))",
     "legendFormat": "CNsec2022全視聴者数"
    },
    {
     "expr": "avg(sum(dreamkast_track_viewer_count{track_id=\"1\"}) by(instance))",
     "legendFormat": "Track A 視聴者数"
    },
    {
     "expr": "avg(sum(dreamkast_track_viewer_count{track_id=\"2\"}) by(instance))",
     "legendFormat": "Track B 視聴者数"
    },
    {
     "expr": "avg(sum(dreamkast_track_viewer_count{track_id=\"3\"}) by(instance))",
     "legendFormat": "Track C 視聴者数"
    }
   ]
  },
  {
   "title": "CNSec2022視聴者数(最新値)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "人" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(dreamkast_viewer_count) by(instance))"
    }
   ]
  },
  {
   "title": "累積チャット数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg(sum(dreamkast_chat_count) by(instance))",
     "legendFormat": "累積チャット数"
    }
   ]
  },
  {
   "title": "累積チャット数(最新値)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(dreamkast_chat_count) by(instance))"
    }
   ]
  },
  {
   "title": "CNSec2022参加登録者数",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg(dreamkast_registrants_count{conference_id=\"6\"})",
     "legendFormat": "CNSec2022登録者数"
    }
   ]
  },
  {
   "title": "CNSec2022参加登録者数(最新値)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "人" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dreamkast_registrants_count{conference_id=\"6\"})"
    }
   ]
  },
  { "title": "Twitter{{$queryString}}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }, "repeat": "queryString" },
  {
   "title": "Twitterダッシュボード使い方",
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "# Twitterダッシュボード使い方\n\n`Twitter関連のメトリクス`を表示するダッシュボードです。\nイベントに関するツイートのいいね数、リツイート数、ツイートの感情分析スコアなど、など、SNS上の反応を表示します。\nハッシュタグ一覧は、ダッシュボードページ最上部左上の`queryString`というプルダウン内から確認できます。\n\n現在表示しているメトリクスは下記の通りです。\n\n- いいね数: イベントに関するハッシュタグを持つ、任意のツイートへのいいね数を表示しています。\n- リツイート数: イベントに関するハッシュタグを持つ、任意のツイートへのリツイート数を表示しています。\n- 感情分析スコア: イベントに関するハッシュタグを持つ、任意のツイート感情分析スコアを表示しています。\n\n"
   }
  },
  {
   "title": "いいね数{{$queryString}}",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "topk(1, social_twitter_favorites{queryString!=\"\", queryString=~\"$queryString\", screenName=\"cloudnativedays\"}) by (tweetId)",
     "legendFormat": "tweetId={{tweetId}}"
    }
   ]
  },
  {
   "title": "リツイート数{{$queryString}}",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "social_twitter_retweets{queryString!=\"\", queryString=~\"$queryString\"}",
     "legendFormat": "tweetId={{tweetId}}"
    }
   ]
  },
  {
   "title": "twitter投稿の感情分析スコア{{$queryString}}",
   "type": "timeseries",
   "description": "twitter 感情分析一覧",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "max(social_twitter_sentiment) by (tweetId) AND max(social_twitter_favorites{queryString=\"$queryString\"}) by (tweetId)",
     "legendFormat": "tweetId={{tweetId}}"
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } }
 ]
}