{
 "title": "Kubernetes Pod",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(exported_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{exported_namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization per Pod [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!=\"\", exported_namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{.pod}}"
    }
   ]
  },
  {
   "title": "Memory utilization per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod!=\"\", exported_namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Disk READ per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(irate(container_fs_reads_bytes_total{pod!=\"\",exported_namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{.pod}}"
    }
   ]
  },
  {
   "title": "Disk WRITE per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(irate(container_fs_writes_bytes_total{pod!=\"\",exported_namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{.pod}}"
    }
   ]
  },
  {
   "title": "Inbound network traffic per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod!=\"\", exported_namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{.pod}}"
    }
   ]
  },
  {
   "title": "Outbound network traffic per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod!=\"\", exported_namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{.pod}}"
    }
   ]
  }
 ]
}