{
 "title": "o11y2022Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "queryString", "query": { "query": "label_values(queryString)" } }
  ]
 },
 "panels": [
  { "title": "Dreamkast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "視聴者数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "sum(dreamkast_viewer_count)" }
   ]
  },
  {
   "title": "累積チャット数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "sum(dreamkast_chat_count)" }
   ]
  },
  {
   "title": "dreamkast_registrants_count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "avg(dreamkast_registrants_count{conference_id=\"5\"})",
     "legendFormat": "o11y2022登録者数"
    }
   ]
  },
  {
   "title": "Twitter{{$queryString}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "queryString",
   "collapsed": true,
   "panels": [
    {
     "title": "いいね数(o11y2022プレイベントデモ用){{$queryString}}",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "social_twitter_favorites{queryString!=\"\", queryString=~\"$queryString\", screenName=\"cloudnativedays\"}"
      }
     ]
    },
    {
     "title": "social_twitter_favorites{{$queryString}}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "social_twitter_favorites{queryString=\"$queryString\"}"
      }
     ]
    },
    {
     "title": "social_twitter_retweets{{$queryString}}",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "social_twitter_retweets{queryString!=\"\", queryString=~\"$queryString\"}"
      }
     ]
    },
    {
     "title": "social_twitter_sentiment{{$queryString}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "max(social_twitter_sentiment) by (tweetId) AND max(social_twitter_favorites{queryString=\"$queryString\"}) by (tweetId)"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "social_twitter_sentiment",
     "type": "timeseries",
     "description": "twitter 感情分析一覧",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "targets": [
      { "expr": "social_twitter_sentiment" }
     ]
    }
   ]
  }
 ]
}