{
 "title": "#o11y2022 proposal",
 "time": { "from": "2021-12-14T15:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count (dreamkast_talks_id)" }
   ]
  },
  {
   "title": "プロポーザル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "count (dreamkast_talks_id)" }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_talks_id) by (talk_difficulty)",
     "legendFormat": "{{talk_difficulty}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*28.*\"})",
     "legendFormat": "Architect - システム設計"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*29.*\"})",
     "legendFormat": "Developer - システム開発"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*30.*\"})",
     "legendFormat": "App-developer - アプリケーション開発"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*31.*\"})",
     "legendFormat": "Operator/sys-admin - 運用管理/システム管理"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*32.*\"})",
     "legendFormat": "Cxo/biz - ビジネス層"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*33.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*34.*\"})",
     "legendFormat": "Dev/qa（開発環境）"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*35.*\"})",
     "legendFormat": "Poc（検証）"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*36.*\"})",
     "legendFormat": "Production（本番環境）"
    }
   ]
  },
  {
   "title": "登壇方法",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"presentation_method\"}) by (params)",
     "legendFormat": "{{params}}"
    }
   ]
  },
  {
   "title": "スライドと動画の公開可否",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\"}) by (params)",
     "legendFormat": "{{params}}"
    }
   ]
  }
 ]
}