{
 "title": "Sentry Monitoring Overview",
 "description": "sentry monitoring overview dashboard",
 "tags": [ "sentry" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Sentry Monitoring Overview Dashboard\n\nSentry とその関連リソースを監視するためのダッシュボードです。概要情報のみ掲載しているため、より詳細な情報を参照したい場合は個別のダッシュボードを参照してください。\n\n- Node の CPU/Memory/Disk 使用率 -> [Node Exporter Full](https://grafana.cloudnativedays.jp/d/rYdddlPWj/node-exporter-full?orgId=1&refresh=1m)\n- Kafka -> [Kafka Exporter Overview](https://grafana.cloudnativedays.jp/d/jwPKIsniz/kafka-exporter-overview?orgId=1)\n- Redis -> [Redis Exporter Quickstart and Dashboard](https://grafana.cloudnativedays.jp/d/bRd48yKMdd/redis-exporter-quickstart-and-dashboard?orgId=1)\n- PostgreSQL -> [PostgreSQL Database](https://grafana.cloudnativedays.jp/d/000000039/postgresql-database?orgId=1&refresh=10s)\n"
   }
  },
  {
   "title": "CPU / Memory / Disk (Sentry Node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"node-exporter:9100\",job=\"sentry-node\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"} - node_memory_Buffers_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"} - node_memory_Cached_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"} - node_memory_Slab_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"} - node_memory_PageTables_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"} - node_memory_SwapCached_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"} - node_memory_SwapFree_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"node-exporter:9100\",job=\"sentry-node\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU / Memory / Disk (Redis Node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"192.168.0.201:9100\",job=\"redis-node\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"} - node_memory_MemFree_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"} - node_memory_Buffers_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"} - node_memory_Cached_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"} - node_memory_Slab_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"} - node_memory_PageTables_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"} - node_memory_SwapCached_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"} - node_memory_SwapFree_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"192.168.0.201:9100\",job=\"redis-node\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Live Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "[Live Logs] self-hosted-sentry",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{compose_project=\"sentry-self-hosted\"}"
    }
   ]
  }
 ]
}