name: ecspresso deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [trigger-ecspresso]

# this workflow should be processed by FIFO
concurrency: ecspresso

permissions:
  contents: read
  id-token: write

jobs:
  ecspresso:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: ap-northeast-1
          role-to-assume: "arn:aws:iam::607167088920:role/github-actions-dreamkast"

      - name: Install ecspresso
        uses: kayac/ecspresso@e048f284f6b81b4f99085a963838c762be99361c # v2

      - name: run ecspresso
        working-directory: ecspresso
        run: |
          # shellcheck disable=SC2016
          find . -name "ecspresso.jsonnet" | grep -v "reviewapps/template" \
            | xargs -I{} -P10 bash -c \
            '[ "$(ecspresso --config={} diff)" = "" ] || ecspresso --config={} deploy'

  ecschedule:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: ap-northeast-1
          role-to-assume: "arn:aws:iam::607167088920:role/github-actions-dreamkast"

      - name: Install ecspresso
        uses: kayac/ecspresso@e048f284f6b81b4f99085a963838c762be99361c # v2

      - name: Install ecschedule
        uses: Songmu/ecschedule@81a8b265305a9979cf4b32bb6220fa1bed19c2a0 # v0.15.1

      - name: register taskdef by ecspresso
        working-directory: ecspresso
        run: |
          # shellcheck disable=SC2016
          find . -name "ecspresso.taskdef.jsonnet" | grep -v "reviewapps/template" \
            | xargs -I{} -P10 bash -c \
            '[ "$(ecspresso --config={} diff)" = "" ] || ecspresso --config={} register'

      - name: ecschedule apply
        working-directory: ecspresso
        run: |
          find . -name "ecschedule.jsonnet" | grep -v "reviewapps/template" \
            | xargs -I{} -P10 bash -c \
            'ecschedule apply -conf {} -all'
